Viajaconmigo/Models/Reporte.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viajaconmigo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reporte
    {
        public int IdReporte { get; set; }
        public int NumeroVentas { get; set; }
        public int TotalDinero { get; set; }
        public int TiquetesVendidos { get; set; }
    }
}

Viajaconmigo/Models/Ventas.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viajaconmigo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ventas
    {
        public int Id_Venta { get; set; }
        public int Cedula_Cliente { get; set; }
        public int Id_Vehiculo_Ruta { get; set; }
        public string Id_Conductor { get; set; }
        public string Id_Despachador { get; set; }
        public int Puestos { get; set; }
        public int TotalPrecio { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Trabajadores Trabajadores { get; set; }
        public virtual Trabajadores Trabajadores1 { get; set; }
        public virtual Vehiculo_Ruta Vehiculo_Ruta { get; set; }
    }
}

Viajaconmigo/Controllers/ReportesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Viajaconmigo.Models;

namespace Viajaconmigo.Controllers
{
    public class ReportesController : Controller
    {
        private viajaconmigoEntities db = new viajaconmigoEntities();

        // GET: Reportes
        public ActionResult Index()
        {
            return View(db.Reporte.ToList());
        }

        // GET: Reportes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reporte reporte = db.Reporte.Find(id);
            if (reporte == null)
            {
                return HttpNotFound();
            }
            return View(reporte);
        }

        // GET: Reportes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Reportes/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdReporte,NumeroVentas,TotalDinero,TiquetesVendidos")] Reporte reporte)
        {
            if (ModelState.IsValid)
            {
                db.Reporte.Add(reporte);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(reporte);
        }

        // GET: Reportes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reporte reporte = db.Reporte.Find(id);
            if (reporte == null)
            {
                return HttpNotFound();
            }
            return View(reporte);
        }

        // POST: Reportes/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdReporte,NumeroVentas,TotalDinero,TiquetesVendidos")] Reporte reporte)
        {
            if (ModelState.IsValid)
            {
                db.Entry(reporte).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(reporte);
        }

        // GET: Reportes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reporte reporte = db.Reporte.Find(id);
            if (reporte == null)
            {
                return HttpNotFound();
            }
            return View(reporte);
        }

        // POST: Reportes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Reporte reporte = db.Reporte.Find(id);
            db.Reporte.Remove(reporte);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Viajaconmigo/Controllers/VentasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Viajaconmigo.Models;

namespace Viajaconmigo.Controllers
{
    public class VentasController : Controller
    {
        private int puestosDisponibles;
        private viajaconmigoEntities db = new viajaconmigoEntities();

        // GET: Ventas
        public ActionResult Index()
        {
            var ventas = db.Ventas.Include(v => v.Cliente).Include(v => v.Trabajadores).Include(v => v.Trabajadores1).Include(v => v.Vehiculo_Ruta);
            return View(ventas.ToList());
        }

        public ActionResult VerAdmin()
        {
            var ventas = db.Ventas.Include(v => v.Cliente).Include(v => v.Trabajadores).Include(v => v.Trabajadores1).Include(v => v.Vehiculo_Ruta);
            return View(ventas.ToList());
        }
        public ActionResult Reporte()
        {

            return View();
        }

        // GET: Ventas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ventas ventas = db.Ventas.Find(id);
            if (ventas == null)
            {
                return HttpNotFound();
            }
            return View(ventas);
        }

        // GET: Ventas/Create
        public ActionResult Create()
        {
            ViewBag.Cedula_Cliente = new SelectList(db.Cliente, "Cedula", "Cedula");
            ViewBag.Id_Conductor = new SelectList(db.Trabajadores, "CodigoTrabajor", "CodigoTrabajor");
            ViewBag.Id_Despachador = new SelectList(db.Trabajadores, "CodigoTrabajor", "CodigoTrabajor");
            ViewBag.Id_Vehiculo_Ruta = new SelectList(db.Vehiculo_Ruta, "Id", "Id");
            return View();
        }

        // POST: Ventas/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id_Venta,Cedula_Cliente,Id_Vehiculo_Ruta,Id_Conductor,Id_Despachador,Puestos")] Ventas ventas)
        {
            puestosDisponibles = restarCupos(ventas.Id_Vehiculo_Ruta, ventas.Puestos);
            Vehiculo_Ruta vehiculo_Ruta = db.Vehiculo_Ruta.Find(ventas.Id_Vehiculo_Ruta);





            if (ModelState.IsValid && puestosDisponibles > 0)
            {
                ventas.TotalPrecio = ventas.Puestos * vehiculo_Ruta.Rutas.Precio;
                db.Ventas.Add(ventas);
                db.SaveChanges();

                GuardarReporte(ventas.TotalPrecio, ventas.Puestos);
                return RedirectToAction("Index");
            }

            ViewBag.Cedula_Cliente = new SelectList(db.Cliente, "Cedula", "Nombre", ventas.Cedula_Cliente);
            ViewBag.Id_Conductor = new SelectList(db.Trabajadores, "CodigoTrabajor", "Nombre", ventas.Id_Conductor);
            ViewBag.Id_Despachador = new SelectList(db.Trabajadores, "CodigoTrabajor", "Nombre", ventas.Id_Despachador);
            ViewBag.Id_Vehiculo_Ruta = new SelectList(db.Vehiculo_Ruta, "Id", "Placa", ventas.Id_Vehiculo_Ruta);
            return View(ventas);

        }

        public void GuardarReporte(int TotalDinero, int Puestos)
        {
            Reporte reporte = db.Reporte.Find(1);

            reporte.NumeroVentas = reporte.NumeroVentas + 1;
            reporte.TiquetesVendidos = Puestos + reporte.TiquetesVendidos;
            reporte.TotalDinero = TotalDinero + reporte.TotalDinero;
            db.Entry(reporte).State = EntityState.Modified;
            db.SaveChanges();
        }

        public int restarCupos(int Id_Vehiculo_Ruta, int puestos)
        {
            Vehiculo_Ruta vehiculo_Ruta = db.Vehiculo_Ruta.Find(Id_Vehiculo_Ruta);
            vehiculo_Ruta.Cupos = vehiculo_Ruta.Cupos - puestos;
            db.Entry(vehiculo_Ruta).State = EntityState.Modified;

            return vehiculo_Ruta.Cupos;
        }

        // GET: Ventas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ventas ventas = db.Ventas.Find(id);
            if (ventas == null)
            {
                return HttpNotFound();
            }
            ViewBag.Cedula_Cliente = new SelectList(db.Cliente, "Cedula", "Cedula", ventas.Cedula_Cliente);
            ViewBag.Id_Conductor = new SelectList(db.Trabajadores, "CodigoTrabajor", "CodigoTrabajor", ventas.Id_Conductor);
            ViewBag.Id_Despachador = new SelectList(db.Trabajadores, "CodigoTrabajor", "CodigoTrabajor", ventas.Id_Despachador);
            ViewBag.Id_Vehiculo_Ruta = new SelectList(db.Vehiculo_Ruta, "Id", "Id", ventas.Id_Vehiculo_Ruta);
            return View(ventas);
        }

        // POST: Ventas/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id_Venta,Cedula_Cliente,Id_Vehiculo_Ruta,Id_Conductor,Id_Despachador")] Ventas ventas)
        {
            if (ModelState.IsValid)
            {
                db.Entry(ventas).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Cedula_Cliente = new SelectList(db.Cliente, "Cedula", "Nombre", ventas.Cedula_Cliente);
            ViewBag.Id_Conductor = new SelectList(db.Trabajadores, "CodigoTrabajor", "Nombre", ventas.Id_Conductor);
            ViewBag.Id_Despachador = new SelectList(db.Trabajadores, "CodigoTrabajor", "Nombre", ventas.Id_Despachador);
            ViewBag.Id_Vehiculo_Ruta = new SelectList(db.Vehiculo_Ruta, "Id", "Placa", ventas.Id_Vehiculo_Ruta);
            return View(ventas);
        }

        // GET: Ventas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ventas ventas = db.Ventas.Find(id);
            if (ventas == null)
            {
                return HttpNotFound();
            }
            return View(ventas);
        }

        // POST: Ventas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Ventas ventas = db.Ventas.Find(id);
            db.Ventas.Remove(ventas);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Viajaconmigo/Views/Ventas/Create.cshtml
@model Viajaconmigo.Models.Ventas

@{
    ViewBag.Title = "Create";
}
<link href="~/Scripts/estilo.css" rel="stylesheet" />
<link href="~/Scripts/style.css" rel="stylesheet" />
<link href="~/Scripts/estiloEmpresas.css" rel="stylesheet" />
<div id="contenedorpagoadmin">
    <div id="cabecera">
        <img src="~/Images/Logo.jpg" width=100% height=100% />
    </div>
    <div id="cuerpopagoadmin">
        <div id="menu">
            <ul id="button">

                <br></br>
                <li><a>@Html.ActionLink("VENTAS", "Index", "Ventas")</a></li>
                <li><a>@Html.ActionLink("REPORTE VENTAS", "Index", "Reportes")</a></li>
                <br></br>
                <br>
            </ul>
        </div>

        <div id="consultepago">

            <div id="verdepago">

                <h1>PAGO EN EFECTIVO</h1>

                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">

                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group2">
                            @Html.LabelFor(model => model.Id_Venta, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Id_Venta, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Id_Venta, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group2">
                            @Html.LabelFor(model => model.Cedula_Cliente, "Cedula_Cliente", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownList("Cedula_Cliente", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.Cedula_Cliente, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group2">
                            @Html.LabelFor(model => model.Id_Vehiculo_Ruta, "Id_Vehiculo_Ruta", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownList("Id_Vehiculo_Ruta", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.Id_Vehiculo_Ruta, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group2">
                            @Html.LabelFor(model => model.Id_Conductor, "Id_Conductor", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownList("Id_Conductor", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.Id_Conductor, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group2">
                            @Html.LabelFor(model => model.Id_Despachador, "Id_Despachador", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownList("Id_Despachador", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.Id_Despachador, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group2">
                            @Html.LabelFor(model => model.Puestos, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Puestos, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Puestos, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <br>
                        <br>
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Ingresar" class="btn btn-default" />
                            </div>
                        </div>
                    </div>
                }

                
            </div>
        </div>



    </div>
    <div id="pie">
        <div id="parte1">
            <h2>Siguenos</h2>
            <h3>
                Telefono: 310 444 77 98<br></br>
                Direccion: Los Cámbulos, Cra. 43 # 65 - 100, Manizales, Caldas <br></br>
                Correo: Viajaconmigo@gmail.com
            </h3>
        </div>
        <div id="parte2">
            <br></br>
            <br></br>
            <br></br>

            <ul id="panel2">
                <center>
                    <li><a href="https://www.facebook.com/viveladorada/"><span class="icon-facebook3"></span></a></li>
                    <li><a href="https://www.instagram.com/viveladorada/"><span class="icon-instagram2"></span></a></li>
                    <li><a href="https://twitter.com/viveladorada"><span class="icon-twitter2"></span></a></li>
                    <li><a href="https://www.youtube.com/channel/UCRFz2LGdzxmTL_j4jIO-UQQ/featured?view_as=subscriber"><span class="icon-youtube3"></span></a></li>
                </center>
            </ul>
            <br></br>
            <br></br>
            <br></br>
            <center><h4>Copyright</h4></center>

        </div>
        <div id="parte3">

            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3974.336019112623!2d-75.5083866852363!3d5.049162696335131!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8e47654245811437%3A0xb0ba16140f5c9cc6!2sTerminal%20de%20Transportes%20de%20Manizales!5e0!3m2!1ses!2sco!4v1574046755482!5m2!1ses!2sco" width="350" height="135" frameborder="0" style="border:0" allowfullscreen></iframe>
        </div>
    </div>
</div>

Viajaconmigo/Views/Ventas/Delete.cshtml
@model Viajaconmigo.Models.Ventas

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Ventas</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Cliente.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cliente.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Trabajadores.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Trabajadores.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Trabajadores1.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Trabajadores1.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Vehiculo_Ruta.Placa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Vehiculo_Ruta.Placa)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Viajaconmigo/Views/Ventas/Details.cshtml
@model Viajaconmigo.Models.Ventas

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Ventas</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Cliente.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cliente.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Trabajadores.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Trabajadores.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Trabajadores1.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Trabajadores1.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Vehiculo_Ruta.Placa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Vehiculo_Ruta.Placa)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id_Venta }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Viajaconmigo/Views/Ventas/Index.cshtml
@model IEnumerable<Viajaconmigo.Models.Ventas>

@{
    ViewBag.Title = "Index";
}

<link href="~/Scripts/estilo.css" rel="stylesheet" />
<link href="~/Scripts/style.css" rel="stylesheet" />
<link href="~/Scripts/estiloEmpresas.css" rel="stylesheet" />
<div id="contenedorpagoadmin">
    <div id="cabecera">
        <img src="~/Images/Logo.jpg" width=100% height=100% />
    </div>
    <div id="cuerpopagoadmin">
        <div id="menu">
            <ul id="button">
                <li> @Html.ActionLink("Inicio", "Create", "Ventas") </li>
            </ul>
        </div>
        <br></br>
        <br>
        <div id="consultepago">

            <h1>VENTAS</h1>

            <form name="frdml">

                <br />
                <table class="table" id="tabladml">
                    <tr>
                        <th id="tabladml1">
                            @Html.DisplayNameFor(model => model.Cliente.Cedula)
                        </th>
                        <th id="tabladml1">
                            @Html.DisplayNameFor(model => model.Id_Despachador)
                        </th>
                        <th id="tabladml1">
                            @Html.DisplayNameFor(model => model.Id_Conductor)
                        </th>
                        <th id="tabladml1">
                            @Html.DisplayNameFor(model => model.Vehiculo_Ruta.Placa)
                        </th>
                        <th id="tabladml1">
                            @Html.DisplayNameFor(model => model.Vehiculo_Ruta.Rutas.Destino)
                        </th>
                        <th id="tabladml1">
                            @Html.DisplayNameFor(model => model.Puestos)
                        </th>
                        <th id="tabladml1">
                            @Html.DisplayNameFor(model => model.TotalPrecio)
                        </th>


                        @foreach (var item in Model)
                        {
                        <tr>
                            <td id="tabladml2">
                                @Html.DisplayFor(modelItem => item.Cliente.Cedula)
                            </td>
                            <td id="tabladml2">
                                @Html.DisplayFor(modelItem => item.Trabajadores1.CodigoTrabajor)
                            </td>
                            <td id="tabladml2">
                                @Html.DisplayFor(modelItem => item.Trabajadores.CodigoTrabajor)
                            </td>
                            <td id="tabladml2">
                                @Html.DisplayFor(modelItem => item.Vehiculo_Ruta.Placa)
                            </td>
                            <td id="tabladml2">
                                @Html.DisplayFor(modelItem => item.Vehiculo_Ruta.Rutas.Destino)
                            </td>
                            <td id="tabladml2">
                                @Html.DisplayFor(modelItem => item.Puestos)
                            </td>
                            <td id="tabladml2">
                                @Html.DisplayFor(modelItem => item.TotalPrecio)
                            </td>

                        </tr>
                    }

                    </table>
                </form>
            </div>
        </div>
        <div id="pie">
            <div id="parte1">
                <h2>Siguenos</h2>
                <h3>
                    Telefono: 310 444 77 98<br></br>
                    Direccion: Los Cámbulos, Cra. 43 # 65 - 100, Manizales, Caldas <br></br>
                    Correo: Viajaconmigo@gmail.com
                </h3>
            </div>
            <div id="parte2">
                <br></br>
                <br></br>
                <br></br>

                <ul id="panel2">
                    <center>
                        <li><a href="https://www.facebook.com/viveladorada/"><span class="icon-facebook3"></span></a></li>
                        <li><a href="https://www.instagram.com/viveladorada/"><span class="icon-instagram2"></span></a></li>
                        <li><a href="https://twitter.com/viveladorada"><span class="icon-twitter2"></span></a></li>
                        <li><a href="https://www.youtube.com/channel/UCRFz2LGdzxmTL_j4jIO-UQQ/featured?view_as=subscriber"><span class="icon-youtube3"></span></a></li>
                    </center>
                </ul>
                <br></br>
                <br></br>
                <br></br>
                <center><h4>Copyright</h4></center>

            </div>
            <div id="parte3">

                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3974.336019112623!2d-75.5083866852363!3d5.049162696335131!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8e47654245811437%3A0xb0ba16140f5c9cc6!2sTerminal%20de%20Transportes%20de%20Manizales!5e0!3m2!1ses!2sco!4v1574046755482!5m2!1ses!2sco" width="350" height="135" frameborder="0" style="border:0" allowfullscreen></iframe>
            </div>
        </div>
    </div>

Viajaconmigo/Views/Ventas/Reporte.cshtml
@model IEnumerable<Viajaconmigo.Models.Ventas>

@{
    ViewBag.Title = "Reporte";
}

<link href="~/Scripts/estilo.css" rel="stylesheet" />
<link href="~/Scripts/style.css" rel="stylesheet" />
<link href="~/Scripts/estiloEmpresas.css" rel="stylesheet" />
<div id="contenedorpagoadmin">
    <div id="cabecera">
        <img src="~/Images/Logo.jpg" width=100% height=100% />
    </div>
    <div id="cuerpopagoadmin">
        <div id="menu">
            <ul id="button">
                <li> @Html.ActionLink("Inicio", "Create", "Ventas") </li>
            </ul>
        </div>
        <br></br>
        <br>
        <div id="consultepago">

            <h1> REPORTE VENTAS</h1>

            <form name="frdml">
            </form>
        </div>
    </div>
    <div id="pie">
        <div id="parte1">
            <h2>Siguenos</h2>
            <h3>
                Telefono: 310 444 77 98<br></br>
                Direccion: Los Cámbulos, Cra. 43 # 65 - 100, Manizales, Caldas <br></br>
                Correo: Viajaconmigo@gmail.com
            </h3>
        </div>
        <div id="parte2">
            <br></br>
            <br></br>
            <br></br>

            <ul id="panel2">
                <center>
                    <li><a href="https://www.facebook.com/viveladorada/"><span class="icon-facebook3"></span></a></li>
                    <li><a href="https://www.instagram.com/viveladorada/"><span class="icon-instagram2"></span></a></li>
                    <li><a href="https://twitter.com/viveladorada"><span class="icon-twitter2"></span></a></li>
                    <li><a href="https://www.youtube.com/channel/UCRFz2LGdzxmTL_j4jIO-UQQ/featured?view_as=subscriber"><span class="icon-youtube3"></span></a></li>
                </center>
            </ul>
            <br></br>
            <br></br>
            <br></br>
            <center><h4>Copyright</h4></center>

        </div>
        <div id="parte3">

            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3974.336019112623!2d-75.5083866852363!3d5.049162696335131!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8e47654245811437%3A0xb0ba16140f5c9cc6!2sTerminal%20de%20Transportes%20de%20Manizales!5e0!3m2!1ses!2sco!4v1574046755482!5m2!1ses!2sco" width="350" height="135" frameborder="0" style="border:0" allowfullscreen></iframe>
        </div>
    </div>
</div>