Viajaconmigo/Controllers/ClientesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Viajaconmigo.Models;

namespace Viajaconmigo.Controllers
{
    public class ClientesController : Controller
    {
        private static string correo, contraseña;
        private viajaconmigoEntities db = new viajaconmigoEntities();

        // GET: Clientes
        public ActionResult Index()
        {
            return View(db.Cliente.ToList());
        }

        // GET: Clientes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cliente cliente = db.Cliente.Find(id);
            if (cliente == null)
            {
                return HttpNotFound();
            }
            return View(cliente);
        }

        // GET: Clientes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Clientes/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Cedula,Nombre,Apellido,Telefono,Direccion,Correo,Password")] Cliente cliente)
        {
            if (ModelState.IsValid)
            {
                db.Cliente.Add(cliente);
                db.SaveChanges();

                correo = cliente.Correo;
                contraseña = cliente.Password;

                GuardarLogin();
                return RedirectToAction("../Home/Logeo");
            }

            return View(cliente);
        }

        public void GuardarLogin()
        {
            Login login = new Login();
            login.Contraseña = contraseña;
            login.Usuario = correo;
            login.TipoUsuario = "1";

            db.Login.Add(login);
            db.SaveChanges();
        }

        // GET: Clientes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cliente cliente = db.Cliente.Find(id);
            if (cliente == null)
            {
                return HttpNotFound();
            }
            return View(cliente);
        }

        // POST: Clientes/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Cedula,Nombre,Apellido,Telefono,Direccion,Correo,Password")] Cliente cliente)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cliente).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(cliente);
        }

        // GET: Clientes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cliente cliente = db.Cliente.Find(id);
            if (cliente == null)
            {
                return HttpNotFound();
            }
            return View(cliente);
        }

        // POST: Clientes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Cliente cliente = db.Cliente.Find(id);
            db.Cliente.Remove(cliente);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Viajaconmigo/Controllers/LoginsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Viajaconmigo.Models;

namespace Viajaconmigo.Controllers
{
    public class LoginsController : Controller
    {
        public bool Iniciar = false;
        private viajaconmigoEntities db = new viajaconmigoEntities();

        // GET: Logins
        public ActionResult Index()
        {
            return View(db.Login.ToList());
        }

        // GET: Logins/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Login login = db.Login.Find(id);
            if (login == null)
            {
                return HttpNotFound();
            }
            return View(login);
        }

        // GET: Logins/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Logins/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Usuario,Contraseña")] Login login)
        {
            Login login1 = db.Login.Find(login.Usuario);

            if (login1 != null)
            {
                if (login.Usuario == login1.Usuario && login.Contraseña == login1.Contraseña)
                {
                    Iniciar = true;
                    if (login1.TipoUsuario == "1")//Cliente
                    {
                        return RedirectToAction("../Home/Inicio");
                    }
                    else if (login1.TipoUsuario == "2")//Admin  
                    {
                        return RedirectToAction("../Home/InicioAdministrador");
                    }
                    else if (login1.TipoUsuario == "3")//Usuario
                    {
                        return RedirectToAction("../Ventas/Index");
                    }

                }
            }

            return View(login);
        }

        // GET: Logins/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Login login = db.Login.Find(id);
            if (login == null)
            {
                return HttpNotFound();
            }
            return View(login);
        }

        // POST: Logins/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Usuario,Contraseña,TipoUsuario")] Login login)
        {
            if (ModelState.IsValid)
            {
                db.Entry(login).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(login);
        }

        // GET: Logins/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Login login = db.Login.Find(id);
            if (login == null)
            {
                return HttpNotFound();
            }
            return View(login);
        }

        // POST: Logins/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Login login = db.Login.Find(id);
            db.Login.Remove(login);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Viajaconmigo/Controllers/RutasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Viajaconmigo.Models;

namespace Viajaconmigo.Controllers
{
    public class RutasController : Controller
    {
        private viajaconmigoEntities db = new viajaconmigoEntities();

        // GET: Rutas
        public ActionResult Index()
        {
            return View(db.Rutas.ToList());
        }

        public ActionResult SearchByDestino(string destino)
        {
            
            if (destino == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            
           return View(db.Vehiculo_Ruta.Where(i=>i.Rutas.Destino == destino).ToList());
        }



        // GET: Rutas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Rutas rutas = db.Rutas.Find(id);
            if (rutas == null)
            {
                return HttpNotFound();
            }
            return View(rutas);
        }

        // GET: Rutas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Rutas/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdRutas,Origen,Destino,Horas_Viaje,Hola_Salida,Precio")] Rutas rutas)
        {
            if (ModelState.IsValid)
            {
                db.Rutas.Add(rutas);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(rutas);
        }

        // GET: Rutas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Rutas rutas = db.Rutas.Find(id);
            if (rutas == null)
            {
                return HttpNotFound();
            }
            return View(rutas);
        }

        // POST: Rutas/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdRutas,Origen,Destino,Horas_Viaje,Hola_Salida,Precio")] Rutas rutas)
        {
            if (ModelState.IsValid)
            {
                db.Entry(rutas).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(rutas);
        }

        // GET: Rutas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Rutas rutas = db.Rutas.Find(id);
            if (rutas == null)
            {
                return HttpNotFound();
            }
            return View(rutas);
        }

        // POST: Rutas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Rutas rutas = db.Rutas.Find(id);
            db.Rutas.Remove(rutas);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


    }
}

Viajaconmigo/Controllers/VehiculoesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Viajaconmigo.Models;

namespace Viajaconmigo.Controllers
{
    public class VehiculoesController : Controller
    {
        private viajaconmigoEntities db = new viajaconmigoEntities();

        // GET: Vehiculoes
        public ActionResult Index()
        {
            var vehiculo = db.Vehiculo.Include(v => v.Empresa);
            return View(vehiculo.ToList());
        }

        // GET: Vehiculoes/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vehiculo vehiculo = db.Vehiculo.Find(id);
            if (vehiculo == null)
            {
                return HttpNotFound();
            }
            return View(vehiculo);
        }

        // GET: Vehiculoes/Create
        public ActionResult Create()
        {
            ViewBag.NitEmpresa = new SelectList(db.Empresa, "NitEmpresa", "Nombre");
            return View();
        }

        // POST: Vehiculoes/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Placa,NitEmpresa,Modelo,Marca,Fecha_Ven_Revision,Fecha_Ven_Soat")] Vehiculo vehiculo)
        {
            if (ModelState.IsValid)
            {
                db.Vehiculo.Add(vehiculo);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.NitEmpresa = new SelectList(db.Empresa, "NitEmpresa", "Nombre", vehiculo.NitEmpresa);
            return View(vehiculo);
        }

        // GET: Vehiculoes/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vehiculo vehiculo = db.Vehiculo.Find(id);
            if (vehiculo == null)
            {
                return HttpNotFound();
            }
            ViewBag.NitEmpresa = new SelectList(db.Empresa, "NitEmpresa", "Nombre", vehiculo.NitEmpresa);
            return View(vehiculo);
        }

        // POST: Vehiculoes/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Placa,NitEmpresa,Modelo,Marca,Fecha_Ven_Revision,Fecha_Ven_Soat")] Vehiculo vehiculo)
        {
            if (ModelState.IsValid)
            {
                db.Entry(vehiculo).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.NitEmpresa = new SelectList(db.Empresa, "NitEmpresa", "Nombre", vehiculo.NitEmpresa);
            return View(vehiculo);
        }

        // GET: Vehiculoes/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vehiculo vehiculo = db.Vehiculo.Find(id);
            if (vehiculo == null)
            {
                return HttpNotFound();
            }
            return View(vehiculo);
        }

        // POST: Vehiculoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Vehiculo vehiculo = db.Vehiculo.Find(id);
            db.Vehiculo.Remove(vehiculo);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Viajaconmigo/Views/Home/Consultas.cshtml
@{
    ViewBag.Title = "Consultas";
}
<link href="~/Scripts/estilo.css" rel="stylesheet" />
<link href="~/Scripts/style.css" rel="stylesheet" />


<div id="contenedor">
    <div id="cabecera">
        <img src="~/Images/Logo.jpg" height="100%" width="100%" />

    </div>
    <div id="cuerpoConsulta">
        <div id="menu">
            <ul id="button">
                <li><a href="#">Login</a></li>

            </ul>
        </div>
        <br></br>

        <div id="consulte1">
            <br></br>
            <h1>RESULTADO DE BUSQUEDA</h1>
            
        </div>
    </div>
    <div id="pie">
        <div id="parte1">
            <h2>Siguenos</h2>
            <h3>
                Telefono: 310 444 77 98<br></br>
                Direccion: Los Cámbulos, Cra. 43 # 65 - 100, Manizales, Caldas <br></br>
                Correo: Viajaconmigo@gmail.com
            </h3>
        </div>
        <div id="parte2">
            <br></br>
            <br></br>
            <br></br>



            <ul id="panel2">
                <center>
                    <li><a href="https://www.facebook.com/viveladorada/"><span class="icon-facebook3"></span></a></li>
                    <li><a href="https://www.instagram.com/viveladorada/"><span class="icon-instagram2"></span></a></li>
                    <li><a href="https://twitter.com/viveladorada"><span class="icon-twitter2"></span></a></li>
                    <li><a href="https://www.youtube.com/channel/UCRFz2LGdzxmTL_j4jIO-UQQ/featured?view_as=subscriber"><span class="icon-youtube3"></span></a></li>
                </center>
            </ul>
            <br></br>
            <br></br>
            <br></br>
            <center><h4>Copyright</h4></center>

        </div>
        <div id="parte3">

            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3974.336019112623!2d-75.5083866852363!3d5.049162696335131!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8e47654245811437%3A0xb0ba16140f5c9cc6!2sTerminal%20de%20Transportes%20de%20Manizales!5e0!3m2!1ses!2sco!4v1574046755482!5m2!1ses!2sco" width="350" height="135" frameborder="0" style="border:0" allowfullscreen></iframe>
        </div>
    </div>
</div>

Viajaconmigo/Views/Home/Dml.cshtml
@{
    ViewBag.Title = "Dml";
}

<link href="~/Scripts/estilo.css" rel="stylesheet" />
<link href="~/Scripts/style.css" rel="stylesheet" />
<link href="~/Scripts/estiloEmpresas.css" rel="stylesheet" />


<div id="contenedordml">
    <div id="cabeceradml">
        <img src="~/Images/Logo.jpg" width=100% height=100% />
        </div>
    
    <div id="cuerpo">
        <br>

        <div id="consultedml">

            <h1>CONSULTA DML</h1>

            <form name="frdml">
                <center>
                    <input type="text14" name"txtNombre" size="30" placeholder="Destino" />
                    <input type="text15" name"txtNombre" size="30" placeholder="Empresa" />

                    <input type="text16" name"txtNombre" size="30" placeholder="Precio" />
                </center>
                <br>

                <center>
                    <input type="text17" name"txtNombre" size="30" placeholder="Horarios" />
                    <input type="text18" name"txtNombre" size="30" placeholder="Tiempo de llegada" />
                </center>
                <br>
                <br>
                <center><button id="button16">Buscar</button></center>
                <br>

                <center>
                    <button id="button17">Insertar</button>

                    <button id="button18">Eliminar</button>

                    <button id="button19">Actualizar</button>
                </center>
                <br>
                <br>

                
            </form>
        
    </div>
</div>
<div id="pie">
    <div id="parte1">
        <h2>Siguenos</h2>
        <h3>
            Telefono: 310 444 77 98<br></br>
            Direccion: Los Cámbulos, Cra. 43 # 65 - 100, Manizales, Caldas <br></br>
            Correo: Viajaconmigo@gmail.com
        </h3>
    </div>
    <div id="parte2">
        <br></br>
        <br></br>
        <br></br>



        <ul id="panel2">
            <center>
                <li><a href="https://www.facebook.com/viveladorada/"><span class="icon-facebook3"></span></a></li>
                <li><a href="https://www.instagram.com/viveladorada/"><span class="icon-instagram2"></span></a></li>
                <li><a href="https://twitter.com/viveladorada"><span class="icon-twitter2"></span></a></li>
                <li><a href="https://www.youtube.com/channel/UCRFz2LGdzxmTL_j4jIO-UQQ/featured?view_as=subscriber"><span class="icon-youtube3"></span></a></li>
            </center>
        </ul>
        <br></br>
        <br></br>
        <br></br>
        <center><h4>Copyright</h4></center>

    </div>
    <div id="parte3">

        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3974.336019112623!2d-75.5083866852363!3d5.049162696335131!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8e47654245811437%3A0xb0ba16140f5c9cc6!2sTerminal%20de%20Transportes%20de%20Manizales!5e0!3m2!1ses!2sco!4v1574046755482!5m2!1ses!2sco" width="350" height="135" frameborder="0" style="border:0" allowfullscreen></iframe>
    </div>
</div>
	</div>

Viajaconmigo/Views/Home/InicioAdministrador.cshtml
@{
    ViewBag.Title = "InicioAdministrador";
}
<link href="~/Scripts/style.css" rel="stylesheet" />
<link href="~/Scripts/estiloEmpresas.css" rel="stylesheet" />
<link href="~/Scripts/estilo.css" rel="stylesheet" />
<div id="contenedorprincipal">
    <div id="cabecera">
        <img src="~/Images/Logo.jpg" width=100% height=100% />
    </div>
    <div id="cuerpoprincipal">
       <br>
        <br>
        
            <div id="consultelogeo">
                <br>
                <h1>ADMINISTRADOR</h1>
                    <br>
                    <form name="frlogeo">
                        <br>
                        <center>
                            <p class="button5"> @Html.ActionLink("RUTAS", "Index", "Rutas") </p>
                            <br>

                            <p class="button5"> @Html.ActionLink("USUARIOS", "Index", "Trabajadores") </p>
                            <br>
                            <p class="button5"> @Html.ActionLink("VEHICULOS", "Index", "Vehiculoes") </p>
                            <br>

                                
                            </center>
                    </form>
                </div>
               
            <div id="empresas">
                <center>
                    <table>
                        <tr>
                            <td><a><img src="~/Images/arauca.png" width=100% height=50% /></a></td>
                            <td><a><img src="~/Images/brasilia.png" width=100% height=50% /></a></td>
                            <td><a><img src="~/Images/AutoLegal.png" width=100% height=50% /></a></td>
                            <td><a><img src="~/Images/coopuertos.png" width=100% height=50% /></a></td>
                            <td><a><img src="~/Images/cafetero.png" width=100% height=50% /></a></td>
                            <td><a><img src="~/Images/cotracol.png" width=100% height=50% /></a></td>
                            <td><a><img src="~/Images/palmira.png" width=100% height=50% /></a></td>
                            <td><a><img src="~/Images/rapidotolima.png" width=100% height=50% /></a></td>
                            <td><a><img src="~/Images/Flota Occidental.png" width=100% height=50% /></a></td>
                            <td><a><img src="~/Images/Flota Ospina.png" width=100% height=50% /></a></td>
                            <td><a><img src="~/Images/Transporte irra.png" width=100% height=50% /></a></td>
                            <td><a><img src="~/Images/TaxLaFeria.png" width=100% height=50% /></a></td>
                        </tr>
                    </table>
                    <table>
                        <tr>
                            <td><a><img src="~/Images/autolujo.png" width=100% height=50% /></a></td>
                            <td><a><img src="~/Images/cootranshuila.png" width=100% height=50% /></a></td>
                            <td><a><img src="~/Images/cootraman.png" width=100% height=50% /></a></td>
                            <td><a><img src="~/Images/cootransnorte.png" width=100% height=50% /></a></td>
                            <td><a><img src="~/Images/cootransrio.png" width=100% height=50% /></a></td>
                            <td><a><img src="~/Images/copetran.png" width=100% height=50% /></a></td>
                            <td><a><img src="~/Images/sideral.png" width=100% height=50% /></a></td>
                            <td><a><img src="~/Images/bolivariano.png" width=100% height=50% /></a></td>
                            <td><a><img src="~/Images/armenia.png" width=100% height=50% /></a></td>
                            <td><a><img src="~/Images/norcaldas.png" width=100% height=50% /></a></td>
                            <td><a><img src="~/Images/alianza.png" width=100% height=50% /></a></td>
                            <td><a><img src="~/Images/trejos.png" width=100% height=50% /></a></td>
                        </tr>
                    </table>
                </center>
            </div>
    </div>

    <div id="pie">
        <div id="parte1">
            <h2>Siguenos</h2>
            <h3>
                Telefono: 310 444 77 98<br></br>
                Direccion: Los Cámbulos, Cra. 43 # 65 - 100, Manizales, Caldas <br></br>
                Correo: Viajaconmigo@gmail.com
            </h3>
        </div>
        <div id="parte2">
            <br></br>
            <br></br>
            <br></br>



            <ul id="panel2">
                <center>
                    <li><a href="https://www.facebook.com/viveladorada/"><span class="icon-facebook3"></span></a></li>
                    <li><a href="https://www.instagram.com/viveladorada/"><span class="icon-instagram2"></span></a></li>
                    <li><a href="https://twitter.com/viveladorada"><span class="icon-twitter2"></span></a></li>
                    <li><a href="https://www.youtube.com/channel/UCRFz2LGdzxmTL_j4jIO-UQQ/featured?view_as=subscriber"><span class="icon-youtube3"></span></a></li>
                </center>
            </ul>
            <br></br>
            <br></br>
            <br></br>
            <center><h4>Copyright</h4></center>

        </div>
        <div id="parte3">

            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3974.336019112623!2d-75.5083866852363!3d5.049162696335131!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8e47654245811437%3A0xb0ba16140f5c9cc6!2sTerminal%20de%20Transportes%20de%20Manizales!5e0!3m2!1ses!2sco!4v1574046755482!5m2!1ses!2sco" width="350" height="135" frameborder="0" style="border:0" allowfullscreen></iframe>
        </div>
    </div>
</div>

Viajaconmigo/Views/Home/Logeo.cshtml
@model IEnumerable<Viajaconmigo.Models.Login>

@{
    ViewBag.Title = "Logeo";
}

<link href="~/Scripts/estilo.css" rel="stylesheet" />
<link href="~/Scripts/style.css" rel="stylesheet" />
<link href="~/Scripts/estiloEmpresas.css" rel="stylesheet" />
<div id="contenedorlogeo">
    <div id="cabecera">

        <img src="~/Images/Logo.jpg" width=100% height=100% />
    </div>
    <div id="cuerpologeo">
        <div id="menu">
            <ul id="button">
                <li> @Html.ActionLink("Inicio", "Index", "Home") </li>
            </ul>
        </div>


        <br></br>

        <br></br>

        <div id="consultelogeo">
            <br></br>
            <div id="logeo">
                <h1>COMO DESEAS INGRESAR</h1>

                <br>


                <form name="frlogeo">
                    <br>
                    <center>
                        <p class="button5"> @Html.ActionLink("Login", "Create", "Logins") </p>

                        <p class="button5"> @Html.ActionLink("Registrarse", "Create", "Clientes") </p>

                    </center>


                    </ul>

                </form>
            </div>

            
        </div>


    </div>
    <div id="pie">
        <div id="parte1">
            <h2>Siguenos</h2>
            <h3>
                Telefono: 310 444 77 98<br></br>
                Direccion: Los Cámbulos, Cra. 43 # 65 - 100, Manizales, Caldas <br></br>
                Correo: Viajaconmigo@gmail.com
            </h3>
        </div>
        <div id="parte2">
            <br></br>
            <br></br>
            <br></br>



            <ul id="panel2">
                <center>
                    <li><a href="https://www.facebook.com/viveladorada/"><span class="icon-facebook3"></span></a></li>
                    <li><a href="https://www.instagram.com/viveladorada/"><span class="icon-instagram2"></span></a></li>
                    <li><a href="https://twitter.com/viveladorada"><span class="icon-twitter2"></span></a></li>
                    <li><a href="https://www.youtube.com/channel/UCRFz2LGdzxmTL_j4jIO-UQQ/featured?view_as=subscriber"><span class="icon-youtube3"></span></a></li>
                </center>
            </ul>
            <br></br>
            <br></br>
            <br></br>
            <center><h4>Copyright</h4></center>

        </div>
        <div id="parte3">

            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3974.336019112623!2d-75.5083866852363!3d5.049162696335131!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8e47654245811437%3A0xb0ba16140f5c9cc6!2sTerminal%20de%20Transportes%20de%20Manizales!5e0!3m2!1ses!2sco!4v1574046755482!5m2!1ses!2sco" width="350" height="135" frameborder="0" style="border:0" allowfullscreen></iframe>
        </div>
    </div>
</div>